### ISSUE TITLE
start OpenMole in such a way it restarts when it stops after an error

### ISSUE THREAD

**Issue by samthiriot** [openmole/openmole#456]
Dear beloved OpenMole community,

When OpenMole stops because of an error, we have to manually connect the server running the instance of OpenMole to restart it. 

Is there a way to start it with a script, as a daemon, or inside a container, so it restarts automatically after a failure? 

Thanks!

**Comment by romainreuillon** [comment]
Dear Samuel,

thank you for your kind return. I would suggest that you use the docker-compose.yml shown at the end of this page:
https://hub.docker.com/repository/docker/openmole/openmole

For 11.2, it would look like this:
```yml
version: "3"

services:
  openmole:
    image: openmole/openmole:$OPENMOLE_VERSION
    hostname: openmole
    volumes:
      - ./data/openmole:/var/openmole/
    ports: 
      - "8080:8080"
    privileged: true
```

Then you could add a restart policy. This would work in case process crashed. 

If it just hangs, the pb is a bit more tedious. You could use a watchdog. The one we use for the demo site looks like:

```
#!/bin/bash

curl --max-time 30 http://demo.openmole.org >/dev/null

RET=$?

if [[ $RET != 0 ]]; then /home/openmole/demo ; fi
```

You should replace the url with the one expose by your docker and the restart command. May be call that from a within a crontask....

Would it be a solution ?

Cheers,
Romain
